### ISSUE TITLE
ES6 classes syntax fails in dev

### ISSUE THREAD

**Issue by nkbt** [nkbt/esnext-quickstart#5]
``` bash
ERROR in ./src/app/Header.js
Module build failed: SyntaxError: /Users/nkbt/nkbt/esnext-quickstart/node_modules/react-hot-loader/index.js!/Users/nkbt/nkbt/esnext-quickstart/node_modules/eslint-loader/index.js!/Users/nkbt/nkbt/esnext-quickstart/src/app/Header.js: 'import' and 'export' may only appear at the top level (6:0)
  4 | 
  5 | 
> 6 | import React from 'react';
    | ^
  7 | 
  8 | 
  9 | export class Header extends React.Component {
    at Parser.pp.raise (/Users/nkbt/nkbt/esnext-quickstart/node_modules/babel-core/lib/acorn/src/location.js:73:13)
    at Parser.pp.parseStatement (/Users/nkbt/nkbt/esnext-quickstart/node_modules/babel-core/lib/acorn/src/statement.js:99:29)
    at Parser.parseStatement (/Users/nkbt/nkbt/esnext-quickstart/node_modules/babel-core/lib/acorn/plugins/flow.js:636:22)
    at Parser.pp.parseBlock (/Users/nkbt/nkbt/esnext-quickstart/node_modules/babel-core/lib/acorn/src/statement.js:387:21)
    at Parser.pp.parseFunctionBody (/Users/nkbt/nkbt/esnext-quickstart/node_modules/babel-core/lib/acorn/src/expression.js:693:22)
    at Parser.parseFunctionBody (/Users/nkbt/nkbt/esnext-quickstart/node_modules/babel-core/lib/acorn/plugins/flow.js:624:20)
    at Parser.pp.parseFunction (/Users/nkbt/nkbt/esnext-quickstart/node_modules/babel-core/lib/acorn/src/statement.js:465:8)
    at Parser.pp.parseExprAtom (/Users/nkbt/nkbt/esnext-quickstart/node_modules/babel-core/lib/acorn/src/expression.js:368:19)
    at Parser.parseExprAtom (/Users/nkbt/nkbt/esnext-quickstart/node_modules/babel-core/node_modules/acorn-jsx/inject.js:624:24)
    at Parser.pp.parseExprSubscripts (/Users/nkbt/nkbt/esnext-quickstart/node_modules/babel-core/lib/acorn/src/expression.js:217:19)
 @ ./src/app/App.js 18:15-34
```

**Comment by nkbt** [comment]
Fixed by changing order of `react-hot` and `babel` loaders
